sudo: required
language: ruby
services:
- docker
script:
- make build-stack-native

after_success:
- if [ "$TRAVIS_BRANCH" == "master" ]; then
  docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
  docker push kejace/hethcon;
  fi
env:
  matrix:
  - secure: n96TMa++4aJ0DYQExVhas8JgwFN1t7vu0nTLuNGJXJe3JoUm9574PPG/ZKuTCD+VDOYi5XThi4DbMfsDzV9s8PHgRZZw/oeMRrzSjWuK0qw7rwrnXQJYEvIQoN/aQnGE21Y0tgY6tBgtdkX1HoC6BeTnV8pN5BKmuaX0vhZkjz4Gzq0y8JsY2iKhBPYdGKXnnA3xOfje4qNOWPF5niSJsMuK754r0AG9sYbFTqNsGjoCx5NSD3lPVLyfoZkLx75O0tII6IGaDQjjYa7/UinCmEHRvrKwzFkqOF+oj4bHaljalkowLpXPvl3FKIAGNFfwnOrg0uhcI4lhJAJviBYjpoPNrujtlopgI481ApwWFn+pK39wc/7d4ikD/SZZkOG0xbyIjj3fibCAlr1tK6wE7rwixFCxEDLBrXNP81z5Tcei+nHLa6izTy3uxLndJYY+8CUJlF0ZjocbD+aQteC6SlG59K7r65lGy0Zqoyv8NmWQowQBXA9qzLSXVfCZ8nEHAFTKtViZX5FGW60tzJmUwf8Aq41jQvvl0GMnMVOcQuX+TVCqVYEsL4Y1AjCZygaF22GDD0Mv71ttYghyoj7ufmihxITS4QPO2FM4oBEAWWQ+roEYpAQvuYNJGwtYKP87IGVa5CR/V4WyFcAP1bWmjN3AlZ8IrOh5NY14eAnvb9Q=
  - secure: Tdp1bGGmQ3LxXrBxrw85lwScjr+/HkwS9bz/7oxIfT9nGWJMKcZUaRya6UAm5TVdnO7Mz7FVfBogT3RDw299/yWveT/ARSp6sd7Bg7m0sNR1zdB0/oXBZ6jbctQNC2muzd1lV++wyiVvfNaX9jmySfiQnMkTcTrVwM3l5M/DnNM8dMoNmFRv51+UPjIi9emYktwLpyqKTetLYfB5/DSf6Q2TUkHg42nl2ZzwEPktwYXu9c7tuQUnoxq1H8zn0gfx2Yr3/3ZO9rjk0RqB3/5txDikfqyltZxM2HNwY4OiLK8hz0Xt25SbPYoGYh1c5oM5N7Y8jWw3tYcLqXbYWb+jAFuX2LVhRVRJaISuTi1jXrqHNwwuGeAmu8InZU7aUw/ni18AonMLwkDCqXC+mhimWpWFhVgSuh6X3ossyJVdVHs5Nrh5bGD3eyp8T432Jfb+l1w7dikwZRBXIEa/ssAzbbX5W/IY3XneNoJQTWOUYO1fPRzAw5iYiZhvRKC7mh5EstwLtnJ+NDdmlUDpdmG8OijD8itLoBW48B680oJgG//Utp9pK3HpeRcoDLgDYYOHJbIWlG0YpjDiVkgAot8AmJShxwFuA7qeOYdxZHIettWWlySrAYByCFVAp89NIziiF3XIu/Uu5f+Ni3Xm0BLM4+1c8KjYUCHE6D06vBRZf1Q=
