resolver: lts-9.10

packages:
  - '.'
  - location:
      git: https://github.com/f-o-a-m/hs-web3
      commit: 2b47af3603b68ef6d2b9f8a9cd6e848b2ad0a224
    extra-dep: true

extra-deps:
  - selda-0.1.11.2
  - sized-0.2.1.1
  - equational-reasoning-0.5.0.0
  - monomorphic-0.0.3.3
  - type-natural-0.7.1.4
  - presburger-1.3.1
  - ghc-typelits-presburger-0.1.1.1
