resolver: lts-9.10

packages:
  - '.'
  - location:
      git: https://github.com/f-o-a-m/hs-web3
      commit: 0e1515ca45f89523ede2926fdc0b033139cd592d
    extra-dep: true
  - location:
      git: https://github.com/f-o-a-m/selda
      commit: 64993ae4f4249df1222691fcb6341367fb8c68d4
      subdirs:
        - selda 
        - selda-postgresql
    extra-dep: true

extra-deps:
  - sized-0.2.1.1
  - equational-reasoning-0.5.0.0
  - monomorphic-0.0.3.3
  - type-natural-0.7.1.4
  - presburger-1.3.1
  - ghc-typelits-presburger-0.1.1.1
